### ISSUE TITLE
Improve asterisk handling

### ISSUE THREAD

**Issue by teamvista** [valrus/undertale-dialog-generator#19]
- [ ] **If Papyrus is chosen, the text box allows you to start the dialogue with an asterisk.**
Canonically, Papyrus's in-game dialogue does not use asterisks.
![image](https://cloud.githubusercontent.com/assets/5490551/12007704/eabe964e-abde-11e5-92b8-3398f90c3308.png)

- [ ] **If text begins with an asterisk, the text should line up properly.**
![image](https://cloud.githubusercontent.com/assets/5490551/12007738/6f987ffa-abe0-11e5-8769-33b000816206.png)
![image](https://cloud.githubusercontent.com/assets/5490551/12007709/02b84f6a-abdf-11e5-8190-a111531847c3.png)

**Comment by valrus** [comment]
- [ ] **If Papyrus is chosen, the text box allows you to start the dialogue with an asterisk.**
I didn't fix this. I agree that Papyrus shouldn't have an asterisk, but it's easy to get right: just don't put an asterisk there. In practice it doesn't appear that many people at all are trying to put erroneous asterisks in Papyrus dialog boxes; if there are people who insist upon it, well, sometimes we just have to [let people be wrong on the Internet](https://xkcd.com/386/) and I think this is such a time.

- [x] **If text begins with an asterisk, the text should line up properly.**
Now THIS, on the other hand, is something I'd been meaning to address for a while, because it's stupendously easy to get wrong and it's frankly irresponsible of me to let people do so. (j/k I have a sense of perspective) (but seriously I lie awake at night knowing that there are Papyrus dialog boxes out there with lowercase text and it's MY FAULT) Anyway, I fixed it. Now the text box (pre-crunchifying) looks like this:
![safari](https://cloud.githubusercontent.com/assets/343665/12014677/a85c430c-ace5-11e5-89f3-99f5a9dee486.png)
There. Screw *that* up, you sloppy text box ingrates.

Thanks for the bug report!
